// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collector.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectRequest struct {
	Cpu                  bool     `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Disk                 bool     `protobuf:"varint,2,opt,name=disk,proto3" json:"disk,omitempty"`
	Network              bool     `protobuf:"varint,3,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRequest) Reset()         { *m = CollectRequest{} }
func (m *CollectRequest) String() string { return proto.CompactTextString(m) }
func (*CollectRequest) ProtoMessage()    {}
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{0}
}

func (m *CollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRequest.Unmarshal(m, b)
}
func (m *CollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRequest.Marshal(b, m, deterministic)
}
func (m *CollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRequest.Merge(m, src)
}
func (m *CollectRequest) XXX_Size() int {
	return xxx_messageInfo_CollectRequest.Size(m)
}
func (m *CollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRequest proto.InternalMessageInfo

func (m *CollectRequest) GetCpu() bool {
	if m != nil {
		return m.Cpu
	}
	return false
}

func (m *CollectRequest) GetDisk() bool {
	if m != nil {
		return m.Disk
	}
	return false
}

func (m *CollectRequest) GetNetwork() bool {
	if m != nil {
		return m.Network
	}
	return false
}

type Domain struct {
	Name                 string           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ID                   uint64           `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Hypervisor           string           `protobuf:"bytes,3,opt,name=Hypervisor,proto3" json:"Hypervisor,omitempty"`
	UUID                 string           `protobuf:"bytes,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	OStype               string           `protobuf:"bytes,5,opt,name=OStype,proto3" json:"OStype,omitempty"`
	Time                 int64            `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	Flags                int32            `protobuf:"varint,7,opt,name=Flags,proto3" json:"Flags,omitempty"`
	CPU                  []*DomainCPU     `protobuf:"bytes,8,rep,name=CPU,proto3" json:"CPU,omitempty"`
	Disk                 []*DomainDisk    `protobuf:"bytes,9,rep,name=Disk,proto3" json:"Disk,omitempty"`
	Network              []*DomainNetwork `protobuf:"bytes,10,rep,name=Network,proto3" json:"Network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{1}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Domain) GetHypervisor() string {
	if m != nil {
		return m.Hypervisor
	}
	return ""
}

func (m *Domain) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Domain) GetOStype() string {
	if m != nil {
		return m.OStype
	}
	return ""
}

func (m *Domain) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Domain) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Domain) GetCPU() []*DomainCPU {
	if m != nil {
		return m.CPU
	}
	return nil
}

func (m *Domain) GetDisk() []*DomainDisk {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *Domain) GetNetwork() []*DomainNetwork {
	if m != nil {
		return m.Network
	}
	return nil
}

type DomainCPU struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Flags                int32    `protobuf:"varint,2,opt,name=Flags,proto3" json:"Flags,omitempty"`
	Time                 float64  `protobuf:"fixed64,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Idle                 float64  `protobuf:"fixed64,4,opt,name=Idle,proto3" json:"Idle,omitempty"`
	IdleSet              bool     `protobuf:"varint,5,opt,name=IdleSet,proto3" json:"IdleSet,omitempty"`
	Idle1                float64  `protobuf:"fixed64,6,opt,name=Idle1,proto3" json:"Idle1,omitempty"`
	Idle5                float64  `protobuf:"fixed64,7,opt,name=Idle5,proto3" json:"Idle5,omitempty"`
	Idle15               float64  `protobuf:"fixed64,8,opt,name=Idle15,proto3" json:"Idle15,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainCPU) Reset()         { *m = DomainCPU{} }
func (m *DomainCPU) String() string { return proto.CompactTextString(m) }
func (*DomainCPU) ProtoMessage()    {}
func (*DomainCPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{2}
}

func (m *DomainCPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainCPU.Unmarshal(m, b)
}
func (m *DomainCPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainCPU.Marshal(b, m, deterministic)
}
func (m *DomainCPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainCPU.Merge(m, src)
}
func (m *DomainCPU) XXX_Size() int {
	return xxx_messageInfo_DomainCPU.Size(m)
}
func (m *DomainCPU) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainCPU.DiscardUnknown(m)
}

var xxx_messageInfo_DomainCPU proto.InternalMessageInfo

func (m *DomainCPU) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DomainCPU) GetFlags() int32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *DomainCPU) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *DomainCPU) GetIdle() float64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *DomainCPU) GetIdleSet() bool {
	if m != nil {
		return m.IdleSet
	}
	return false
}

func (m *DomainCPU) GetIdle1() float64 {
	if m != nil {
		return m.Idle1
	}
	return 0
}

func (m *DomainCPU) GetIdle5() float64 {
	if m != nil {
		return m.Idle5
	}
	return 0
}

func (m *DomainCPU) GetIdle15() float64 {
	if m != nil {
		return m.Idle15
	}
	return 0
}

type DomainDisk struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ReadOnly             bool     `protobuf:"varint,2,opt,name=ReadOnly,proto3" json:"ReadOnly,omitempty"`
	IsDisk               bool     `protobuf:"varint,3,opt,name=IsDisk,proto3" json:"IsDisk,omitempty"`
	IsCDRom              bool     `protobuf:"varint,4,opt,name=IsCDRom,proto3" json:"IsCDRom,omitempty"`
	Read                 *BlockIO `protobuf:"bytes,5,opt,name=Read,proto3" json:"Read,omitempty"`
	Write                *BlockIO `protobuf:"bytes,6,opt,name=Write,proto3" json:"Write,omitempty"`
	Flush                *BlockIO `protobuf:"bytes,7,opt,name=Flush,proto3" json:"Flush,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainDisk) Reset()         { *m = DomainDisk{} }
func (m *DomainDisk) String() string { return proto.CompactTextString(m) }
func (*DomainDisk) ProtoMessage()    {}
func (*DomainDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{3}
}

func (m *DomainDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainDisk.Unmarshal(m, b)
}
func (m *DomainDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainDisk.Marshal(b, m, deterministic)
}
func (m *DomainDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainDisk.Merge(m, src)
}
func (m *DomainDisk) XXX_Size() int {
	return xxx_messageInfo_DomainDisk.Size(m)
}
func (m *DomainDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainDisk.DiscardUnknown(m)
}

var xxx_messageInfo_DomainDisk proto.InternalMessageInfo

func (m *DomainDisk) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainDisk) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *DomainDisk) GetIsDisk() bool {
	if m != nil {
		return m.IsDisk
	}
	return false
}

func (m *DomainDisk) GetIsCDRom() bool {
	if m != nil {
		return m.IsCDRom
	}
	return false
}

func (m *DomainDisk) GetRead() *BlockIO {
	if m != nil {
		return m.Read
	}
	return nil
}

func (m *DomainDisk) GetWrite() *BlockIO {
	if m != nil {
		return m.Write
	}
	return nil
}

func (m *DomainDisk) GetFlush() *BlockIO {
	if m != nil {
		return m.Flush
	}
	return nil
}

type BlockIO struct {
	Operations           uint64   `protobuf:"varint,1,opt,name=Operations,proto3" json:"Operations,omitempty"`
	Bytes                uint64   `protobuf:"varint,2,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Sectors              uint64   `protobuf:"varint,3,opt,name=Sectors,proto3" json:"Sectors,omitempty"`
	Absolute             bool     `protobuf:"varint,4,opt,name=Absolute,proto3" json:"Absolute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockIO) Reset()         { *m = BlockIO{} }
func (m *BlockIO) String() string { return proto.CompactTextString(m) }
func (*BlockIO) ProtoMessage()    {}
func (*BlockIO) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{4}
}

func (m *BlockIO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockIO.Unmarshal(m, b)
}
func (m *BlockIO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockIO.Marshal(b, m, deterministic)
}
func (m *BlockIO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockIO.Merge(m, src)
}
func (m *BlockIO) XXX_Size() int {
	return xxx_messageInfo_BlockIO.Size(m)
}
func (m *BlockIO) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockIO.DiscardUnknown(m)
}

var xxx_messageInfo_BlockIO proto.InternalMessageInfo

func (m *BlockIO) GetOperations() uint64 {
	if m != nil {
		return m.Operations
	}
	return 0
}

func (m *BlockIO) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *BlockIO) GetSectors() uint64 {
	if m != nil {
		return m.Sectors
	}
	return 0
}

func (m *BlockIO) GetAbsolute() bool {
	if m != nil {
		return m.Absolute
	}
	return false
}

type DomainNetwork struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mac                  *NetworkHWAddr `protobuf:"bytes,2,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Bridges              []string       `protobuf:"bytes,3,rep,name=Bridges,proto3" json:"Bridges,omitempty"`
	RX                   *NetworkIO     `protobuf:"bytes,4,opt,name=RX,proto3" json:"RX,omitempty"`
	TX                   *NetworkIO     `protobuf:"bytes,5,opt,name=TX,proto3" json:"TX,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DomainNetwork) Reset()         { *m = DomainNetwork{} }
func (m *DomainNetwork) String() string { return proto.CompactTextString(m) }
func (*DomainNetwork) ProtoMessage()    {}
func (*DomainNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{5}
}

func (m *DomainNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainNetwork.Unmarshal(m, b)
}
func (m *DomainNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainNetwork.Marshal(b, m, deterministic)
}
func (m *DomainNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainNetwork.Merge(m, src)
}
func (m *DomainNetwork) XXX_Size() int {
	return xxx_messageInfo_DomainNetwork.Size(m)
}
func (m *DomainNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_DomainNetwork proto.InternalMessageInfo

func (m *DomainNetwork) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainNetwork) GetMac() *NetworkHWAddr {
	if m != nil {
		return m.Mac
	}
	return nil
}

func (m *DomainNetwork) GetBridges() []string {
	if m != nil {
		return m.Bridges
	}
	return nil
}

func (m *DomainNetwork) GetRX() *NetworkIO {
	if m != nil {
		return m.RX
	}
	return nil
}

func (m *DomainNetwork) GetTX() *NetworkIO {
	if m != nil {
		return m.TX
	}
	return nil
}

type NetworkHWAddr struct {
	Mac                  string   `protobuf:"bytes,1,opt,name=Mac,proto3" json:"Mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkHWAddr) Reset()         { *m = NetworkHWAddr{} }
func (m *NetworkHWAddr) String() string { return proto.CompactTextString(m) }
func (*NetworkHWAddr) ProtoMessage()    {}
func (*NetworkHWAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{6}
}

func (m *NetworkHWAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkHWAddr.Unmarshal(m, b)
}
func (m *NetworkHWAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkHWAddr.Marshal(b, m, deterministic)
}
func (m *NetworkHWAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkHWAddr.Merge(m, src)
}
func (m *NetworkHWAddr) XXX_Size() int {
	return xxx_messageInfo_NetworkHWAddr.Size(m)
}
func (m *NetworkHWAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkHWAddr.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkHWAddr proto.InternalMessageInfo

func (m *NetworkHWAddr) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type NetworkIO struct {
	Bytes                uint64   `protobuf:"varint,1,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Packets              uint64   `protobuf:"varint,2,opt,name=Packets,proto3" json:"Packets,omitempty"`
	Errors               uint64   `protobuf:"varint,3,opt,name=Errors,proto3" json:"Errors,omitempty"`
	Drops                uint64   `protobuf:"varint,4,opt,name=Drops,proto3" json:"Drops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkIO) Reset()         { *m = NetworkIO{} }
func (m *NetworkIO) String() string { return proto.CompactTextString(m) }
func (*NetworkIO) ProtoMessage()    {}
func (*NetworkIO) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{7}
}

func (m *NetworkIO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkIO.Unmarshal(m, b)
}
func (m *NetworkIO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkIO.Marshal(b, m, deterministic)
}
func (m *NetworkIO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkIO.Merge(m, src)
}
func (m *NetworkIO) XXX_Size() int {
	return xxx_messageInfo_NetworkIO.Size(m)
}
func (m *NetworkIO) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkIO.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkIO proto.InternalMessageInfo

func (m *NetworkIO) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *NetworkIO) GetPackets() uint64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *NetworkIO) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *NetworkIO) GetDrops() uint64 {
	if m != nil {
		return m.Drops
	}
	return 0
}

type Suspend struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suspend) Reset()         { *m = Suspend{} }
func (m *Suspend) String() string { return proto.CompactTextString(m) }
func (*Suspend) ProtoMessage()    {}
func (*Suspend) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{8}
}

func (m *Suspend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suspend.Unmarshal(m, b)
}
func (m *Suspend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suspend.Marshal(b, m, deterministic)
}
func (m *Suspend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suspend.Merge(m, src)
}
func (m *Suspend) XXX_Size() int {
	return xxx_messageInfo_Suspend.Size(m)
}
func (m *Suspend) XXX_DiscardUnknown() {
	xxx_messageInfo_Suspend.DiscardUnknown(m)
}

var xxx_messageInfo_Suspend proto.InternalMessageInfo

func (m *Suspend) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Suspend) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Suspend) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type Unsuspend struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unsuspend) Reset()         { *m = Unsuspend{} }
func (m *Unsuspend) String() string { return proto.CompactTextString(m) }
func (*Unsuspend) ProtoMessage()    {}
func (*Unsuspend) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{9}
}

func (m *Unsuspend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unsuspend.Unmarshal(m, b)
}
func (m *Unsuspend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unsuspend.Marshal(b, m, deterministic)
}
func (m *Unsuspend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unsuspend.Merge(m, src)
}
func (m *Unsuspend) XXX_Size() int {
	return xxx_messageInfo_Unsuspend.Size(m)
}
func (m *Unsuspend) XXX_DiscardUnknown() {
	xxx_messageInfo_Unsuspend.DiscardUnknown(m)
}

var xxx_messageInfo_Unsuspend proto.InternalMessageInfo

func (m *Unsuspend) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type LimitCPU struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitCPU) Reset()         { *m = LimitCPU{} }
func (m *LimitCPU) String() string { return proto.CompactTextString(m) }
func (*LimitCPU) ProtoMessage()    {}
func (*LimitCPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{10}
}

func (m *LimitCPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitCPU.Unmarshal(m, b)
}
func (m *LimitCPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitCPU.Marshal(b, m, deterministic)
}
func (m *LimitCPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitCPU.Merge(m, src)
}
func (m *LimitCPU) XXX_Size() int {
	return xxx_messageInfo_LimitCPU.Size(m)
}
func (m *LimitCPU) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitCPU.DiscardUnknown(m)
}

var xxx_messageInfo_LimitCPU proto.InternalMessageInfo

type UnlimitCPU struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlimitCPU) Reset()         { *m = UnlimitCPU{} }
func (m *UnlimitCPU) String() string { return proto.CompactTextString(m) }
func (*UnlimitCPU) ProtoMessage()    {}
func (*UnlimitCPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{11}
}

func (m *UnlimitCPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlimitCPU.Unmarshal(m, b)
}
func (m *UnlimitCPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlimitCPU.Marshal(b, m, deterministic)
}
func (m *UnlimitCPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlimitCPU.Merge(m, src)
}
func (m *UnlimitCPU) XXX_Size() int {
	return xxx_messageInfo_UnlimitCPU.Size(m)
}
func (m *UnlimitCPU) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlimitCPU.DiscardUnknown(m)
}

var xxx_messageInfo_UnlimitCPU proto.InternalMessageInfo

type LimitDisk struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitDisk) Reset()         { *m = LimitDisk{} }
func (m *LimitDisk) String() string { return proto.CompactTextString(m) }
func (*LimitDisk) ProtoMessage()    {}
func (*LimitDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{12}
}

func (m *LimitDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitDisk.Unmarshal(m, b)
}
func (m *LimitDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitDisk.Marshal(b, m, deterministic)
}
func (m *LimitDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitDisk.Merge(m, src)
}
func (m *LimitDisk) XXX_Size() int {
	return xxx_messageInfo_LimitDisk.Size(m)
}
func (m *LimitDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitDisk.DiscardUnknown(m)
}

var xxx_messageInfo_LimitDisk proto.InternalMessageInfo

type UnlimitDisk struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlimitDisk) Reset()         { *m = UnlimitDisk{} }
func (m *UnlimitDisk) String() string { return proto.CompactTextString(m) }
func (*UnlimitDisk) ProtoMessage()    {}
func (*UnlimitDisk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{13}
}

func (m *UnlimitDisk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlimitDisk.Unmarshal(m, b)
}
func (m *UnlimitDisk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlimitDisk.Marshal(b, m, deterministic)
}
func (m *UnlimitDisk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlimitDisk.Merge(m, src)
}
func (m *UnlimitDisk) XXX_Size() int {
	return xxx_messageInfo_UnlimitDisk.Size(m)
}
func (m *UnlimitDisk) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlimitDisk.DiscardUnknown(m)
}

var xxx_messageInfo_UnlimitDisk proto.InternalMessageInfo

type LimitNetwork struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LimitNetwork) Reset()         { *m = LimitNetwork{} }
func (m *LimitNetwork) String() string { return proto.CompactTextString(m) }
func (*LimitNetwork) ProtoMessage()    {}
func (*LimitNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{14}
}

func (m *LimitNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LimitNetwork.Unmarshal(m, b)
}
func (m *LimitNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LimitNetwork.Marshal(b, m, deterministic)
}
func (m *LimitNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LimitNetwork.Merge(m, src)
}
func (m *LimitNetwork) XXX_Size() int {
	return xxx_messageInfo_LimitNetwork.Size(m)
}
func (m *LimitNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_LimitNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_LimitNetwork proto.InternalMessageInfo

type UnlimitNetwork struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlimitNetwork) Reset()         { *m = UnlimitNetwork{} }
func (m *UnlimitNetwork) String() string { return proto.CompactTextString(m) }
func (*UnlimitNetwork) ProtoMessage()    {}
func (*UnlimitNetwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{15}
}

func (m *UnlimitNetwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlimitNetwork.Unmarshal(m, b)
}
func (m *UnlimitNetwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlimitNetwork.Marshal(b, m, deterministic)
}
func (m *UnlimitNetwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlimitNetwork.Merge(m, src)
}
func (m *UnlimitNetwork) XXX_Size() int {
	return xxx_messageInfo_UnlimitNetwork.Size(m)
}
func (m *UnlimitNetwork) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlimitNetwork.DiscardUnknown(m)
}

var xxx_messageInfo_UnlimitNetwork proto.InternalMessageInfo

type BlockSMTP struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSMTP) Reset()         { *m = BlockSMTP{} }
func (m *BlockSMTP) String() string { return proto.CompactTextString(m) }
func (*BlockSMTP) ProtoMessage()    {}
func (*BlockSMTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{16}
}

func (m *BlockSMTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSMTP.Unmarshal(m, b)
}
func (m *BlockSMTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSMTP.Marshal(b, m, deterministic)
}
func (m *BlockSMTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSMTP.Merge(m, src)
}
func (m *BlockSMTP) XXX_Size() int {
	return xxx_messageInfo_BlockSMTP.Size(m)
}
func (m *BlockSMTP) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSMTP.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSMTP proto.InternalMessageInfo

func (m *BlockSMTP) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BlockSMTP) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BlockSMTP) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UnblockSMTP struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnblockSMTP) Reset()         { *m = UnblockSMTP{} }
func (m *UnblockSMTP) String() string { return proto.CompactTextString(m) }
func (*UnblockSMTP) ProtoMessage()    {}
func (*UnblockSMTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{17}
}

func (m *UnblockSMTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnblockSMTP.Unmarshal(m, b)
}
func (m *UnblockSMTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnblockSMTP.Marshal(b, m, deterministic)
}
func (m *UnblockSMTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnblockSMTP.Merge(m, src)
}
func (m *UnblockSMTP) XXX_Size() int {
	return xxx_messageInfo_UnblockSMTP.Size(m)
}
func (m *UnblockSMTP) XXX_DiscardUnknown() {
	xxx_messageInfo_UnblockSMTP.DiscardUnknown(m)
}

var xxx_messageInfo_UnblockSMTP proto.InternalMessageInfo

func (m *UnblockSMTP) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UnblockSMTP) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UnblockSMTP) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{18}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameResponse) Reset()         { *m = NameResponse{} }
func (m *NameResponse) String() string { return proto.CompactTextString(m) }
func (*NameResponse) ProtoMessage()    {}
func (*NameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{19}
}

func (m *NameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameResponse.Unmarshal(m, b)
}
func (m *NameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameResponse.Marshal(b, m, deterministic)
}
func (m *NameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameResponse.Merge(m, src)
}
func (m *NameResponse) XXX_Size() int {
	return xxx_messageInfo_NameResponse.Size(m)
}
func (m *NameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NameResponse proto.InternalMessageInfo

func (m *NameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DetectResponse struct {
	IsHypervisor         bool     `protobuf:"varint,1,opt,name=isHypervisor,proto3" json:"isHypervisor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectResponse) Reset()         { *m = DetectResponse{} }
func (m *DetectResponse) String() string { return proto.CompactTextString(m) }
func (*DetectResponse) ProtoMessage()    {}
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9305884a292fdf82, []int{20}
}

func (m *DetectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectResponse.Unmarshal(m, b)
}
func (m *DetectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectResponse.Marshal(b, m, deterministic)
}
func (m *DetectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectResponse.Merge(m, src)
}
func (m *DetectResponse) XXX_Size() int {
	return xxx_messageInfo_DetectResponse.Size(m)
}
func (m *DetectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectResponse proto.InternalMessageInfo

func (m *DetectResponse) GetIsHypervisor() bool {
	if m != nil {
		return m.IsHypervisor
	}
	return false
}

func init() {
	proto.RegisterType((*CollectRequest)(nil), "protocol.CollectRequest")
	proto.RegisterType((*Domain)(nil), "protocol.Domain")
	proto.RegisterType((*DomainCPU)(nil), "protocol.DomainCPU")
	proto.RegisterType((*DomainDisk)(nil), "protocol.DomainDisk")
	proto.RegisterType((*BlockIO)(nil), "protocol.BlockIO")
	proto.RegisterType((*DomainNetwork)(nil), "protocol.DomainNetwork")
	proto.RegisterType((*NetworkHWAddr)(nil), "protocol.NetworkHWAddr")
	proto.RegisterType((*NetworkIO)(nil), "protocol.NetworkIO")
	proto.RegisterType((*Suspend)(nil), "protocol.Suspend")
	proto.RegisterType((*Unsuspend)(nil), "protocol.Unsuspend")
	proto.RegisterType((*LimitCPU)(nil), "protocol.LimitCPU")
	proto.RegisterType((*UnlimitCPU)(nil), "protocol.UnlimitCPU")
	proto.RegisterType((*LimitDisk)(nil), "protocol.LimitDisk")
	proto.RegisterType((*UnlimitDisk)(nil), "protocol.UnlimitDisk")
	proto.RegisterType((*LimitNetwork)(nil), "protocol.LimitNetwork")
	proto.RegisterType((*UnlimitNetwork)(nil), "protocol.UnlimitNetwork")
	proto.RegisterType((*BlockSMTP)(nil), "protocol.BlockSMTP")
	proto.RegisterType((*UnblockSMTP)(nil), "protocol.UnblockSMTP")
	proto.RegisterType((*Empty)(nil), "protocol.Empty")
	proto.RegisterType((*NameResponse)(nil), "protocol.NameResponse")
	proto.RegisterType((*DetectResponse)(nil), "protocol.DetectResponse")
}

func init() { proto.RegisterFile("collector.proto", fileDescriptor_9305884a292fdf82) }

var fileDescriptor_9305884a292fdf82 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x92, 0xdb, 0x44,
	0x10, 0x2e, 0xd9, 0xf2, 0x8f, 0xda, 0x5e, 0x67, 0x19, 0x52, 0x41, 0xb5, 0x07, 0x30, 0x43, 0xa5,
	0x70, 0x2e, 0x0b, 0xd9, 0xb0, 0xc5, 0x39, 0x6b, 0x25, 0x15, 0x17, 0x24, 0x36, 0x63, 0xbb, 0xe2,
	0xab, 0xd6, 0x9a, 0x0a, 0x2a, 0xcb, 0x1a, 0xa1, 0x91, 0x96, 0xf2, 0x0b, 0xf1, 0x00, 0x5c, 0x78,
	0x0f, 0x5e, 0x82, 0xd7, 0xa0, 0xba, 0x67, 0x64, 0xcb, 0x5e, 0x73, 0xe3, 0xa4, 0xfe, 0xba, 0x7b,
	0x7a, 0xfa, 0xfb, 0xa6, 0x35, 0x03, 0x4f, 0xd6, 0x2a, 0x49, 0xe4, 0xba, 0x50, 0xf9, 0x75, 0x96,
	0xab, 0x42, 0xb1, 0x2e, 0x7d, 0xd6, 0x2a, 0xe1, 0x33, 0x18, 0x8c, 0x4d, 0x50, 0xc8, 0xdf, 0x4a,
	0xa9, 0x0b, 0x76, 0x09, 0xcd, 0x75, 0x56, 0xfa, 0xce, 0xd0, 0x19, 0x75, 0x05, 0x9a, 0x8c, 0x81,
	0x1b, 0xc5, 0x7a, 0xe3, 0x37, 0xc8, 0x45, 0x36, 0xf3, 0xa1, 0x93, 0xca, 0xe2, 0x77, 0x95, 0x6f,
	0xfc, 0x26, 0xb9, 0x2b, 0xc8, 0xff, 0x68, 0x40, 0x3b, 0x50, 0xdb, 0x30, 0x4e, 0x71, 0xe1, 0x87,
	0x70, 0x2b, 0xa9, 0x96, 0x27, 0xc8, 0x66, 0x03, 0x68, 0x4c, 0x02, 0x2a, 0xe5, 0x8a, 0xc6, 0x24,
	0x60, 0x5f, 0x02, 0xbc, 0xdb, 0x65, 0x32, 0x7f, 0x88, 0xb5, 0xca, 0xa9, 0x96, 0x27, 0x6a, 0x1e,
	0xac, 0xb1, 0x5c, 0x4e, 0x02, 0xdf, 0x35, 0x35, 0xd0, 0x66, 0xcf, 0xa0, 0x3d, 0x9d, 0x17, 0xbb,
	0x4c, 0xfa, 0x2d, 0xf2, 0x5a, 0x84, 0xb9, 0x8b, 0x78, 0x2b, 0xfd, 0xf6, 0xd0, 0x19, 0x35, 0x05,
	0xd9, 0xec, 0x29, 0xb4, 0xde, 0x26, 0xe1, 0x27, 0xed, 0x77, 0x86, 0xce, 0xa8, 0x25, 0x0c, 0x60,
	0xcf, 0xa1, 0x39, 0x9e, 0x2d, 0xfd, 0xee, 0xb0, 0x39, 0xea, 0xdd, 0x7c, 0x7e, 0x5d, 0xc9, 0x71,
	0x6d, 0x1a, 0x1f, 0xcf, 0x96, 0x02, 0xe3, 0x6c, 0x04, 0x6e, 0x80, 0xcc, 0x3d, 0xca, 0x7b, 0x7a,
	0x9a, 0x87, 0x31, 0x41, 0x19, 0xec, 0x25, 0x74, 0x3e, 0x58, 0x3d, 0x80, 0x92, 0xbf, 0x38, 0x4d,
	0xb6, 0x61, 0x51, 0xe5, 0xf1, 0xbf, 0x1c, 0xf0, 0xf6, 0xfb, 0x59, 0x5d, 0x9c, 0xbd, 0x2e, 0xfb,
	0xbe, 0x1b, 0xf5, 0xbe, 0x2b, 0x86, 0xa8, 0x93, 0x63, 0x19, 0x32, 0x70, 0x27, 0x51, 0x22, 0x49,
	0x21, 0x47, 0x90, 0x8d, 0xc7, 0x83, 0xdf, 0xb9, 0x2c, 0x48, 0xa2, 0xae, 0xa8, 0x20, 0xd6, 0x45,
	0xf3, 0x25, 0x89, 0xe4, 0x08, 0x03, 0x2a, 0xef, 0x2d, 0xa9, 0x64, 0xbd, 0xb7, 0xa8, 0x33, 0x85,
	0x6f, 0xfd, 0x2e, 0xb9, 0x2d, 0xe2, 0xff, 0x38, 0x00, 0x07, 0x05, 0xce, 0x1e, 0xf3, 0x15, 0x74,
	0x85, 0x0c, 0xa3, 0x69, 0x9a, 0xec, 0xec, 0xdc, 0xec, 0x31, 0x95, 0xd5, 0xa4, 0xab, 0x19, 0x1d,
	0x8b, 0xa8, 0x69, 0x3d, 0x0e, 0x84, 0xda, 0x12, 0x17, 0x6c, 0xda, 0x40, 0xf6, 0x1c, 0x5c, 0x5c,
	0x4d, 0x5c, 0x7a, 0x37, 0x9f, 0x1d, 0xa4, 0xbd, 0x4b, 0xd4, 0x7a, 0x33, 0x99, 0x0a, 0x0a, 0xb3,
	0x6f, 0xa1, 0xf5, 0x31, 0x8f, 0x0b, 0x33, 0x00, 0x67, 0xf3, 0x4c, 0x1c, 0x13, 0xdf, 0x26, 0xa5,
	0xfe, 0x95, 0xe8, 0x9e, 0x4f, 0xa4, 0x38, 0x2f, 0xa1, 0x63, 0x3d, 0x38, 0xa8, 0xd3, 0x4c, 0xe6,
	0x61, 0x11, 0xab, 0x54, 0xdb, 0x83, 0xaa, 0x79, 0x50, 0xc2, 0xbb, 0x5d, 0x21, 0xb5, 0x9d, 0x6d,
	0x03, 0x90, 0xd3, 0x9c, 0xfe, 0x3c, 0x4d, 0x64, 0x5d, 0x51, 0x41, 0x54, 0xe8, 0xf5, 0xbd, 0x56,
	0x49, 0x59, 0x48, 0x4b, 0x77, 0x8f, 0xf9, 0x9f, 0x0e, 0x5c, 0x1c, 0x4d, 0xcd, 0x59, 0x8d, 0x5f,
	0x40, 0xf3, 0x7d, 0xb8, 0xa6, 0xfd, 0x8e, 0xe6, 0xcd, 0xae, 0x79, 0xf7, 0xf1, 0x75, 0x14, 0xe5,
	0x02, 0x73, 0xb0, 0x8d, 0xbb, 0x3c, 0x8e, 0x3e, 0x49, 0x6c, 0xa3, 0x39, 0xf2, 0x44, 0x05, 0xd9,
	0x37, 0xd0, 0x10, 0x2b, 0x6a, 0xe0, 0xe8, 0x47, 0xb0, 0x35, 0x26, 0x53, 0xd1, 0x10, 0x2b, 0x4c,
	0x5a, 0xac, 0xac, 0xfa, 0xe7, 0x93, 0x16, 0x2b, 0xfe, 0x35, 0x5c, 0x1c, 0xed, 0x8c, 0x37, 0x09,
	0xf6, 0x67, 0x5a, 0x46, 0x93, 0xc7, 0xe0, 0xed, 0xd7, 0x1c, 0x04, 0x73, 0x4e, 0x04, 0x9b, 0x85,
	0xeb, 0x8d, 0x2c, 0x2a, 0x21, 0x2b, 0x88, 0x63, 0xf3, 0x26, 0xcf, 0x0f, 0x4a, 0x5a, 0x84, 0x75,
	0x82, 0x5c, 0x65, 0x9a, 0x48, 0xb8, 0xc2, 0x00, 0xfe, 0x0b, 0x74, 0xe6, 0xa5, 0xce, 0x64, 0x1a,
	0xa1, 0x76, 0x65, 0x19, 0x47, 0x95, 0x76, 0x68, 0x63, 0xb1, 0x5c, 0x86, 0x5a, 0xa5, 0xb4, 0x8b,
	0x27, 0x2c, 0xc2, 0x53, 0x89, 0x4a, 0x73, 0xa4, 0xb4, 0x4d, 0x4b, 0xec, 0x31, 0xff, 0x0a, 0xbc,
	0x65, 0xaa, 0xff, 0xbb, 0x28, 0x07, 0xe8, 0xfe, 0x1c, 0x6f, 0xe3, 0x62, 0x3c, 0x5b, 0xf2, 0x3e,
	0xc0, 0x32, 0x4d, 0x2a, 0xd4, 0x03, 0x8f, 0x22, 0x38, 0xe7, 0xfc, 0x02, 0x7a, 0x36, 0x44, 0x70,
	0x00, 0x7d, 0x8a, 0x55, 0xf7, 0xc2, 0x25, 0x0c, 0x6c, 0xb8, 0xf2, 0x4c, 0xc0, 0xa3, 0x29, 0x9c,
	0xbf, 0x5f, 0xcc, 0xce, 0xb2, 0x61, 0xe0, 0xd2, 0x75, 0x68, 0xb8, 0x90, 0x8d, 0xb2, 0x3c, 0x84,
	0x49, 0x29, 0xed, 0x9d, 0x6a, 0x00, 0xff, 0x09, 0xf7, 0xbe, 0xff, 0x9f, 0x8a, 0x75, 0xa0, 0xf5,
	0x66, 0x9b, 0x15, 0x3b, 0xce, 0xa1, 0x8f, 0x13, 0x29, 0xa4, 0xce, 0x54, 0xaa, 0xe9, 0x4a, 0x4a,
	0x6b, 0xd3, 0x8a, 0x36, 0xff, 0x01, 0x06, 0x81, 0x2c, 0xe8, 0xa1, 0xb1, 0x59, 0x1c, 0xfa, 0xb1,
	0xae, 0x5d, 0xfe, 0xe6, 0xc9, 0x39, 0xf2, 0xdd, 0xfc, 0xed, 0x40, 0x3b, 0xc8, 0xe3, 0x07, 0x99,
	0xb3, 0x1f, 0xa1, 0x63, 0x9f, 0x2a, 0xe6, 0x1f, 0x66, 0xf0, 0xf8, 0xf5, 0xba, 0xba, 0x3c, 0xbd,
	0x76, 0xbf, 0x77, 0xd8, 0x0b, 0x68, 0x8d, 0x13, 0xa5, 0x25, 0x7b, 0x72, 0x08, 0x52, 0xdf, 0x57,
	0xa7, 0x0e, 0xf6, 0x9d, 0xf9, 0xcd, 0x1e, 0x67, 0x3e, 0xab, 0x4d, 0x7d, 0x9d, 0xe9, 0x2b, 0x68,
	0x1b, 0x56, 0x8f, 0x97, 0xd4, 0x9a, 0x3c, 0x26, 0x7e, 0xdf, 0xa6, 0xc0, 0xab, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x24, 0xab, 0x52, 0x60, 0x98, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriverClient interface {
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Driver_CollectClient, error)
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error)
	Detect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DetectResponse, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Driver_CollectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Driver_serviceDesc.Streams[0], "/protocol.Driver/Collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverCollectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_CollectClient interface {
	Recv() (*Domain, error)
	grpc.ClientStream
}

type driverCollectClient struct {
	grpc.ClientStream
}

func (x *driverCollectClient) Recv() (*Domain, error) {
	m := new(Domain)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protocol.Driver/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Name(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NameResponse, error) {
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, "/protocol.Driver/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Detect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DetectResponse, error) {
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, "/protocol.Driver/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServer is the server API for Driver service.
type DriverServer interface {
	Collect(*CollectRequest, Driver_CollectServer) error
	Close(context.Context, *Empty) (*Empty, error)
	Name(context.Context, *Empty) (*NameResponse, error)
	Detect(context.Context, *Empty) (*DetectResponse, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Collect(m, &driverCollectServer{stream})
}

type Driver_CollectServer interface {
	Send(*Domain) error
	grpc.ServerStream
}

type driverCollectServer struct {
	grpc.ServerStream
}

func (x *driverCollectServer) Send(m *Domain) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Driver/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Driver/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Name(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Driver/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Detect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Close",
			Handler:    _Driver_Close_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _Driver_Name_Handler,
		},
		{
			MethodName: "Detect",
			Handler:    _Driver_Detect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _Driver_Collect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "collector.proto",
}
